// Code generated by wit-bindgen-go. DO NOT EDIT.

package api

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "csil:arena/api".
var Exports struct {
	// Player represents the caller-defined exports for resource "csil:arena/api#player".
	Player struct {
		// Destructor represents the caller-defined, exported destructor for resource "player".
		//
		// Resource destructor.
		Destructor func(self cm.Rep)

		// Constructor represents the caller-defined, exported constructor for resource "player".
		//
		//	constructor(bytes: list<u8>)
		Constructor func(bytes cm.List[uint8]) (result Player)

		// Play represents the caller-defined, exported method "play".
		//
		//	play: func(bytes: list<u8>) -> s64
		Play func(self cm.Rep, bytes cm.List[uint8]) (result int64)
	}
}
