package csil:arena;

interface api {
  resource player {
    constructor(bytes: list<u8>);
    play: func(bytes: list<u8>) -> s64;
  }
}

world arena-player {
  // needed for go
  // include wasi:cli/imports@0.2.0;

  export api;
}
